---
title: "main"
author: "Julián Alcázar"
date: "2026-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Librarias necesarias

```{r}
library(writexl)
library(readxl)
library(dplyr)
```

# Usa una expresión regular para buscar todos los ficheros de puntuaciones en la carpeta descomprimida
# Usa una expresión regular para buscar todos los ficheros con el justificante del curso. 

```{r}
ficheros <- list.files("data", recursive = TRUE, full.names = TRUE)
fs_puntos <- ficheros[grep("puntos.*\\.txt$", ficheros, ignore.case = TRUE)]
fs_certificados <- ficheros[grep("certificate.*\\.pdf$", ficheros, ignore.case = TRUE)]
```

# Data frame 

```{r}
carpetas <- list.dirs("data", recursive = FALSE)
apellidos = c()
puntos <- c()
noms_f_puntos <- c()
contenidos_f_puntos <- c()

for (carpeta in carpetas) {
  partes_ruta <- unlist(strsplit(carpeta, "/"))
  carpeta_alumno <- partes_ruta[2]
  
  nombre_completo <- unlist(strsplit(carpeta_alumno, "_"))[1]
  
  partes_nombre <- unlist(strsplit(nombre_completo, ","))
  apellido_sucio <- partes_nombre[1]
  
  apellidos <- c(apellidos, apellido_sucio)
  
  f_alumno <- list.files(carpeta, full.names = TRUE)
  f_puntos <- f_alumno[grep("puntos.*\\.txt$", f_alumno, ignore.case = TRUE)]
  
  if (length(f_puntos) == 1) {
    nom_f_puntos <- basename(f_puntos[1])
    noms_f_puntos <- c(noms_f_puntos, nom_f_puntos)
    
    linea_puntos <- readLines(f_puntos[1], warn = FALSE)
    
    texto_completo <- paste(linea_puntos, collapse = " ")
    contenidos_f_puntos <- c(contenidos_f_puntos, texto_completo)
    
    if (length(linea_puntos) >= 1) {
      valor <- as.numeric(gsub("[^0-9]", "", linea_puntos[1]))
      
      if (is.na(valor)) {
        puntos <- c(puntos, 0)
      } else {
        puntos <- c(puntos, valor)
      }
    } else {
      puntos <- c(puntos, 0)
    }
    
  } else {
    puntos <- c(puntos, 0)
    noms_f_puntos <- c(noms_f_puntos, "NA")
    contenidos_f_puntos <- c(contenidos_f_puntos, "Fichero no encontrado")
  }
}

# Los archivos que no tienen el nombre nada bien (Score2.pdf) no se pueden encontrar.
apellidos
puntos
noms_f_puntos
contenidos_f_puntos

notasRIntermedio <- data.frame(
  apellidos = apellidos,
  puntos = puntos,
  NomFile = noms_f_puntos,
  Puntos = contenidos_f_puntos,
  stringsAsFactors = FALSE
)
notasRIntermedio <- notasRIntermedio[order(notasRIntermedio$apellidos), ]
notasRIntermedio
```

# Creación del .Xlsx de NotasRIntermedio 

```{r}
write_xlsx(notasRIntermedio, path = "InfoAlumnos/NotasRIntermedio.xlsx")
```

# Creación del .xlsx de AlumnosNotas-xlsx

```{r}
alumnos_matriculados <- read_excel("InfoAlumnos/AlumnosTD25_26.xlsx")

alumnos_matriculados <- alumnos_matriculados |>
  rename(Apellidos_Original = "Apellido(s)") |> 
  mutate(apellidos = trimws(Apellidos_Original))

notasRIntermedio <- notasRIntermedio |>
  mutate(apellidos = trimws(apellidos))

alumnos_notas_final <- alumnos_matriculados |>
  left_join(notasRIntermedio, by = "apellidos")

alumnos_notas_final <- alumnos_notas_final |>
  select(-Apellidos_Original) |>
  rename(Apellidos = apellidos)

write_xlsx(alumnos_notas_final, "InfoAlumnos/AlumnosNotas.xlsx")
```